//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.Extensions.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.Extensions.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a Key-Value pair into an existing Dictionary.
        /// </summary>
        public static string AddToDictionary_Description {
            get {
                return ResourceManager.GetString("AddToDictionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary to insert the key-value pair into.
        /// </summary>
        public static string AddToDictionary_Dictionary_Description {
            get {
                return ResourceManager.GetString("AddToDictionary_Dictionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string AddToDictionary_Dictionary_DisplayName {
            get {
                return ResourceManager.GetString("AddToDictionary_Dictionary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToDictionary.
        /// </summary>
        public static string AddToDictionary_DisplayName {
            get {
                return ResourceManager.GetString("AddToDictionary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key associated with the value.
        /// </summary>
        public static string AddToDictionary_Key_Description {
            get {
                return ResourceManager.GetString("AddToDictionary_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string AddToDictionary_Key_DisplayName {
            get {
                return ResourceManager.GetString("AddToDictionary_Key_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value associated with the key.
        /// </summary>
        public static string AddToDictionary_Value_Description {
            get {
                return ResourceManager.GetString("AddToDictionary_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AddToDictionary_Value_DisplayName {
            get {
                return ResourceManager.GetString("AddToDictionary_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User story: As an RPA Developer, I want to use an activity that will determine if a specific Key exists within a given Dictionary. The activity will provide a Boolean results as to whether a provided Key exists within a provided Dictionary. When the given key exists, then value will be returned. When the given key is does not exists, a null is returned for the value..
        /// </summary>
        public static string ContainsKey_Description {
            get {
                return ResourceManager.GetString("ContainsKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainsKey.
        /// </summary>
        public static string ContainsKey_DisplayName {
            get {
                return ResourceManager.GetString("ContainsKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary to query.
        /// </summary>
        public static string ContainsKey_In_dictionary_Description {
            get {
                return ResourceManager.GetString("ContainsKey_In_dictionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in_dictionary.
        /// </summary>
        public static string ContainsKey_In_dictionary_DisplayName {
            get {
                return ResourceManager.GetString("ContainsKey_In_dictionary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key to inspect.
        /// </summary>
        public static string ContainsKey_In_key_Description {
            get {
                return ResourceManager.GetString("ContainsKey_In_key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in_key.
        /// </summary>
        public static string ContainsKey_In_key_DisplayName {
            get {
                return ResourceManager.GetString("ContainsKey_In_key_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean on presence of key.
        /// </summary>
        public static string ContainsKey_Out_result_Description {
            get {
                return ResourceManager.GetString("ContainsKey_Out_result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out_result.
        /// </summary>
        public static string ContainsKey_Out_result_DisplayName {
            get {
                return ResourceManager.GetString("ContainsKey_Out_result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in the dictionary.
        /// </summary>
        public static string ContainsKey_Out_value_Description {
            get {
                return ResourceManager.GetString("ContainsKey_Out_value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out_value.
        /// </summary>
        public static string ContainsKey_Out_value_DisplayName {
            get {
                return ResourceManager.GetString("ContainsKey_Out_value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFromDictionary_Description {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveFromDictionary.
        /// </summary>
        public static string RemoveFromDictionary_DisplayName {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFromDictionary_In_Dictionary_Description {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_In_Dictionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in_Dictionary.
        /// </summary>
        public static string RemoveFromDictionary_In_Dictionary_DisplayName {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_In_Dictionary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFromDictionary_In_Key_Description {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_In_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in_Key.
        /// </summary>
        public static string RemoveFromDictionary_In_Key_DisplayName {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_In_Key_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFromDictionary_Out_Result_Description {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_Out_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out_Result.
        /// </summary>
        public static string RemoveFromDictionary_Out_Result_DisplayName {
            get {
                return ResourceManager.GetString("RemoveFromDictionary_Out_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
